version: '2'

services:
  app:
    image: 'zhenyaaa50/tinkoff-image-transformer:2.0.0'
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db/postgres
      - MINIO.URL=http://minio

  db:
    image: 'postgres:16-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./environment/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  postgres:
  storage-minio: